typography_spectrum: 0.6722107143141329
color:
  brandColors:
    - '#ED1C24'
    - '#897763'
    - '#000000'
    - '#FFFFFF'
    - '#FDB813'
  brandStrength: 0.4375
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9317937
analytics:
  google: null
  facebook: null
  twitter: null
name: Personalizingit
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: personalizingit
    url: 'Http:/www.personalizingit.com'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Personalizing-It Inc
description: Leo
purpose: []
